/**
 * Multi-Country Configuration
 *
 * Each country has its own:
 * - Currency and pricing
 * - Phone validation
 * - Payment methods
 * - Categories
 * - Localized content
 */

export interface CountryConfig {
  code: string // ISO 3166-1 alpha-2
  name: string
  flag: string // emoji
  currency: string
  currencySymbol: string
  currencyPosition: 'before' | 'after'
  phonePrefix: string
  phoneLength: number // digits after country code
  paymentMethods: ('carrier' | 'payfast' | 'paystack' | 'stripe' | 'mpesa' | 'flutterwave')[]
  categories: string[]
  provinces?: string[] // states/provinces/regions
  timezone: string
  enabled: boolean
  backgroundImage?: string // URL to country-specific background image
}

export const countries: Record<string, CountryConfig> = {
  sa: {
    code: 'ZA',
    name: 'South Africa',
    flag: '🇿🇦',
    currency: 'ZAR',
    currencySymbol: 'R',
    currencyPosition: 'before',
    phonePrefix: '+27',
    phoneLength: 9,
    paymentMethods: ['carrier', 'payfast'],
    categories: [
      'BREAKING',
      'TRAFFIC',
      'CRIME',
      'PROTEST',
      'LOADSHEDDING',
      'WEATHER',
      'COMMUNITY',
      'POLITICS',
      'OTHER',
    ],
    provinces: [
      'Gauteng',
      'Western Cape',
      'KwaZulu-Natal',
      'Eastern Cape',
      'Free State',
      'Limpopo',
      'Mpumalanga',
      'North West',
      'Northern Cape',
    ],
    timezone: 'Africa/Johannesburg',
    enabled: true,
    backgroundImage: 'https://media.saleaks.co.za/background.png',
  },
  ng: {
    code: 'NG',
    name: 'Nigeria',
    flag: '🇳🇬',
    currency: 'NGN',
    currencySymbol: '₦',
    currencyPosition: 'before',
    phonePrefix: '+234',
    phoneLength: 10,
    paymentMethods: ['paystack', 'flutterwave'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'FUEL_SCARCITY',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Lagos',
      'Abuja',
      'Rivers',
      'Kano',
      'Oyo',
      'Kaduna',
      'Delta',
      'Anambra',
      'Other',
    ],
    timezone: 'Africa/Lagos',
    enabled: true,
    backgroundImage: 'https://media.saleaks.co.za/backgroundnigeria.png',
  },
  ke: {
    code: 'KE',
    name: 'Kenya',
    flag: '🇰🇪',
    currency: 'KES',
    currencySymbol: 'KSh',
    currencyPosition: 'before',
    phonePrefix: '+254',
    phoneLength: 9,
    paymentMethods: ['mpesa', 'stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Nairobi',
      'Mombasa',
      'Kisumu',
      'Nakuru',
      'Eldoret',
      'Other',
    ],
    timezone: 'Africa/Nairobi',
    enabled: true,
  },
  gh: {
    code: 'GH',
    name: 'Ghana',
    flag: '🇬🇭',
    currency: 'GHS',
    currencySymbol: 'GH₵',
    currencyPosition: 'before',
    phonePrefix: '+233',
    phoneLength: 9,
    paymentMethods: ['flutterwave', 'stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Greater Accra',
      'Ashanti',
      'Central',
      'Western',
      'Eastern',
      'Other',
    ],
    timezone: 'Africa/Accra',
    enabled: true,
  },
  us: {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    currency: 'USD',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [], // Too many states to list
    timezone: 'America/New_York',
    enabled: true,
  },
  uk: {
    code: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    currency: 'GBP',
    currencySymbol: '£',
    currencyPosition: 'before',
    phonePrefix: '+44',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'England',
      'Scotland',
      'Wales',
      'Northern Ireland',
    ],
    timezone: 'Europe/London',
    enabled: true,
  },
  // Africa
  zw: {
    code: 'ZW',
    name: 'Zimbabwe',
    flag: '🇿🇼',
    currency: 'USD',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+263',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Harare',
      'Bulawayo',
      'Manicaland',
      'Mashonaland',
      'Matabeleland',
      'Midlands',
      'Masvingo',
      'Other',
    ],
    timezone: 'Africa/Harare',
    enabled: true,
  },
  eg: {
    code: 'EG',
    name: 'Egypt',
    flag: '🇪🇬',
    currency: 'EGP',
    currencySymbol: 'E£',
    currencyPosition: 'before',
    phonePrefix: '+20',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Cairo',
      'Alexandria',
      'Giza',
      'Luxor',
      'Aswan',
      'Other',
    ],
    timezone: 'Africa/Cairo',
    enabled: true,
  },
  ma: {
    code: 'MA',
    name: 'Morocco',
    flag: '🇲🇦',
    currency: 'MAD',
    currencySymbol: 'MAD',
    currencyPosition: 'after',
    phonePrefix: '+212',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Casablanca',
      'Rabat',
      'Marrakech',
      'Fes',
      'Tangier',
      'Other',
    ],
    timezone: 'Africa/Casablanca',
    enabled: true,
  },
  tz: {
    code: 'TZ',
    name: 'Tanzania',
    flag: '🇹🇿',
    currency: 'TZS',
    currencySymbol: 'TSh',
    currencyPosition: 'before',
    phonePrefix: '+255',
    phoneLength: 9,
    paymentMethods: ['mpesa', 'stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Dar es Salaam',
      'Dodoma',
      'Arusha',
      'Mwanza',
      'Zanzibar',
      'Other',
    ],
    timezone: 'Africa/Dar_es_Salaam',
    enabled: true,
  },
  ug: {
    code: 'UG',
    name: 'Uganda',
    flag: '🇺🇬',
    currency: 'UGX',
    currencySymbol: 'USh',
    currencyPosition: 'before',
    phonePrefix: '+256',
    phoneLength: 9,
    paymentMethods: ['mpesa', 'stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Kampala',
      'Entebbe',
      'Jinja',
      'Gulu',
      'Mbarara',
      'Other',
    ],
    timezone: 'Africa/Kampala',
    enabled: true,
  },
  et: {
    code: 'ET',
    name: 'Ethiopia',
    flag: '🇪🇹',
    currency: 'ETB',
    currencySymbol: 'Br',
    currencyPosition: 'before',
    phonePrefix: '+251',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Addis Ababa',
      'Dire Dawa',
      'Oromia',
      'Amhara',
      'Tigray',
      'Other',
    ],
    timezone: 'Africa/Addis_Ababa',
    enabled: true,
  },
  // Europe
  de: {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+49',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Berlin',
      'Bavaria',
      'Hamburg',
      'North Rhine-Westphalia',
      'Baden-Württemberg',
      'Other',
    ],
    timezone: 'Europe/Berlin',
    enabled: true,
  },
  fr: {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+33',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Île-de-France',
      'Provence-Alpes-Côte d\'Azur',
      'Auvergne-Rhône-Alpes',
      'Nouvelle-Aquitaine',
      'Occitanie',
      'Other',
    ],
    timezone: 'Europe/Paris',
    enabled: true,
  },
  es: {
    code: 'ES',
    name: 'Spain',
    flag: '🇪🇸',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+34',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Madrid',
      'Catalonia',
      'Andalusia',
      'Valencia',
      'Basque Country',
      'Other',
    ],
    timezone: 'Europe/Madrid',
    enabled: true,
  },
  it: {
    code: 'IT',
    name: 'Italy',
    flag: '🇮🇹',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+39',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Lombardy',
      'Lazio',
      'Campania',
      'Sicily',
      'Veneto',
      'Other',
    ],
    timezone: 'Europe/Rome',
    enabled: true,
  },
  nl: {
    code: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+31',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'North Holland',
      'South Holland',
      'Utrecht',
      'North Brabant',
      'Gelderland',
      'Other',
    ],
    timezone: 'Europe/Amsterdam',
    enabled: true,
  },
  ie: {
    code: 'IE',
    name: 'Ireland',
    flag: '🇮🇪',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+353',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Dublin',
      'Cork',
      'Galway',
      'Limerick',
      'Waterford',
      'Other',
    ],
    timezone: 'Europe/Dublin',
    enabled: true,
  },
  // Asia
  ind: {
    code: 'IN',
    name: 'India',
    flag: '🇮🇳',
    currency: 'INR',
    currencySymbol: '₹',
    currencyPosition: 'before',
    phonePrefix: '+91',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Maharashtra',
      'Delhi',
      'Karnataka',
      'Tamil Nadu',
      'West Bengal',
      'Other',
    ],
    timezone: 'Asia/Kolkata',
    enabled: true,
  },
  pk: {
    code: 'PK',
    name: 'Pakistan',
    flag: '🇵🇰',
    currency: 'PKR',
    currencySymbol: '₨',
    currencyPosition: 'before',
    phonePrefix: '+92',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Punjab',
      'Sindh',
      'Khyber Pakhtunkhwa',
      'Balochistan',
      'Islamabad',
      'Other',
    ],
    timezone: 'Asia/Karachi',
    enabled: true,
  },
  ph: {
    code: 'PH',
    name: 'Philippines',
    flag: '🇵🇭',
    currency: 'PHP',
    currencySymbol: '₱',
    currencyPosition: 'before',
    phonePrefix: '+63',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Metro Manila',
      'Cebu',
      'Davao',
      'Calabarzon',
      'Central Luzon',
      'Other',
    ],
    timezone: 'Asia/Manila',
    enabled: true,
  },
  idn: {
    code: 'ID',
    name: 'Indonesia',
    flag: '🇮🇩',
    currency: 'IDR',
    currencySymbol: 'Rp',
    currencyPosition: 'before',
    phonePrefix: '+62',
    phoneLength: 11,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Jakarta',
      'West Java',
      'East Java',
      'Central Java',
      'Bali',
      'Other',
    ],
    timezone: 'Asia/Jakarta',
    enabled: true,
  },
  my: {
    code: 'MY',
    name: 'Malaysia',
    flag: '🇲🇾',
    currency: 'MYR',
    currencySymbol: 'RM',
    currencyPosition: 'before',
    phonePrefix: '+60',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Kuala Lumpur',
      'Selangor',
      'Penang',
      'Johor',
      'Sabah',
      'Sarawak',
      'Other',
    ],
    timezone: 'Asia/Kuala_Lumpur',
    enabled: true,
  },
  sg: {
    code: 'SG',
    name: 'Singapore',
    flag: '🇸🇬',
    currency: 'SGD',
    currencySymbol: 'S$',
    currencyPosition: 'before',
    phonePrefix: '+65',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [],
    timezone: 'Asia/Singapore',
    enabled: true,
  },
  // Americas
  ca: {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    currency: 'CAD',
    currencySymbol: 'C$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Ontario',
      'Quebec',
      'British Columbia',
      'Alberta',
      'Manitoba',
      'Other',
    ],
    timezone: 'America/Toronto',
    enabled: true,
  },
  mx: {
    code: 'MX',
    name: 'Mexico',
    flag: '🇲🇽',
    currency: 'MXN',
    currencySymbol: 'MX$',
    currencyPosition: 'before',
    phonePrefix: '+52',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Mexico City',
      'Jalisco',
      'Nuevo León',
      'Yucatán',
      'Quintana Roo',
      'Other',
    ],
    timezone: 'America/Mexico_City',
    enabled: true,
  },
  br: {
    code: 'BR',
    name: 'Brazil',
    flag: '🇧🇷',
    currency: 'BRL',
    currencySymbol: 'R$',
    currencyPosition: 'before',
    phonePrefix: '+55',
    phoneLength: 11,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'São Paulo',
      'Rio de Janeiro',
      'Minas Gerais',
      'Bahia',
      'Paraná',
      'Other',
    ],
    timezone: 'America/Sao_Paulo',
    enabled: true,
  },
  ar: {
    code: 'AR',
    name: 'Argentina',
    flag: '🇦🇷',
    currency: 'ARS',
    currencySymbol: 'AR$',
    currencyPosition: 'before',
    phonePrefix: '+54',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Buenos Aires',
      'Córdoba',
      'Santa Fe',
      'Mendoza',
      'Tucumán',
      'Other',
    ],
    timezone: 'America/Argentina/Buenos_Aires',
    enabled: true,
  },
  co: {
    code: 'CO',
    name: 'Colombia',
    flag: '🇨🇴',
    currency: 'COP',
    currencySymbol: 'CO$',
    currencyPosition: 'before',
    phonePrefix: '+57',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Bogotá',
      'Antioquia',
      'Valle del Cauca',
      'Atlántico',
      'Santander',
      'Other',
    ],
    timezone: 'America/Bogota',
    enabled: true,
  },
  // Oceania
  au: {
    code: 'AU',
    name: 'Australia',
    flag: '🇦🇺',
    currency: 'AUD',
    currencySymbol: 'A$',
    currencyPosition: 'before',
    phonePrefix: '+61',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'New South Wales',
      'Victoria',
      'Queensland',
      'Western Australia',
      'South Australia',
      'Tasmania',
      'Other',
    ],
    timezone: 'Australia/Sydney',
    enabled: true,
  },
  nz: {
    code: 'NZ',
    name: 'New Zealand',
    flag: '🇳🇿',
    currency: 'NZD',
    currencySymbol: 'NZ$',
    currencyPosition: 'before',
    phonePrefix: '+64',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Auckland',
      'Wellington',
      'Canterbury',
      'Waikato',
      'Otago',
      'Other',
    ],
    timezone: 'Pacific/Auckland',
    enabled: true,
  },
  // Middle East
  ae: {
    code: 'AE',
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    currency: 'AED',
    currencySymbol: 'AED',
    currencyPosition: 'before',
    phonePrefix: '+971',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Dubai',
      'Abu Dhabi',
      'Sharjah',
      'Ajman',
      'Other',
    ],
    timezone: 'Asia/Dubai',
    enabled: true,
  },
  ksa: {
    code: 'SA',
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    currency: 'SAR',
    currencySymbol: 'SAR',
    currencyPosition: 'before',
    phonePrefix: '+966',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Riyadh',
      'Makkah',
      'Eastern Province',
      'Madinah',
      'Other',
    ],
    timezone: 'Asia/Riyadh',
    enabled: true,
  },
  il: {
    code: 'IL',
    name: 'Israel',
    flag: '🇮🇱',
    currency: 'ILS',
    currencySymbol: '₪',
    currencyPosition: 'before',
    phonePrefix: '+972',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Tel Aviv',
      'Jerusalem',
      'Haifa',
      'Central District',
      'Other',
    ],
    timezone: 'Asia/Jerusalem',
    enabled: true,
  },
  // ============ ADDITIONAL AFRICAN COUNTRIES ============
  dz: {
    code: 'DZ',
    name: 'Algeria',
    flag: '🇩🇿',
    currency: 'DZD',
    currencySymbol: 'د.ج',
    currencyPosition: 'after',
    phonePrefix: '+213',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Other'],
    timezone: 'Africa/Algiers',
    enabled: true,
  },
  tn: {
    code: 'TN',
    name: 'Tunisia',
    flag: '🇹🇳',
    currency: 'TND',
    currencySymbol: 'د.ت',
    currencyPosition: 'after',
    phonePrefix: '+216',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Tunis', 'Sfax', 'Sousse', 'Other'],
    timezone: 'Africa/Tunis',
    enabled: true,
  },
  ly: {
    code: 'LY',
    name: 'Libya',
    flag: '🇱🇾',
    currency: 'LYD',
    currencySymbol: 'ل.د',
    currencyPosition: 'after',
    phonePrefix: '+218',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Tripoli', 'Benghazi', 'Misrata', 'Other'],
    timezone: 'Africa/Tripoli',
    enabled: true,
  },
  sd: {
    code: 'SD',
    name: 'Sudan',
    flag: '🇸🇩',
    currency: 'SDG',
    currencySymbol: 'ج.س',
    currencyPosition: 'after',
    phonePrefix: '+249',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Khartoum', 'Omdurman', 'Port Sudan', 'Other'],
    timezone: 'Africa/Khartoum',
    enabled: true,
  },
  ss: {
    code: 'SS',
    name: 'South Sudan',
    flag: '🇸🇸',
    currency: 'SSP',
    currencySymbol: '£',
    currencyPosition: 'before',
    phonePrefix: '+211',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Juba', 'Other'],
    timezone: 'Africa/Juba',
    enabled: true,
  },
  sn: {
    code: 'SN',
    name: 'Senegal',
    flag: '🇸🇳',
    currency: 'XOF',
    currencySymbol: 'CFA',
    currencyPosition: 'after',
    phonePrefix: '+221',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Dakar', 'Thiès', 'Saint-Louis', 'Other'],
    timezone: 'Africa/Dakar',
    enabled: true,
  },
  ci: {
    code: 'CI',
    name: 'Côte d\'Ivoire',
    flag: '🇨🇮',
    currency: 'XOF',
    currencySymbol: 'CFA',
    currencyPosition: 'after',
    phonePrefix: '+225',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Abidjan', 'Yamoussoukro', 'Bouaké', 'Other'],
    timezone: 'Africa/Abidjan',
    enabled: true,
  },
  cm: {
    code: 'CM',
    name: 'Cameroon',
    flag: '🇨🇲',
    currency: 'XAF',
    currencySymbol: 'FCFA',
    currencyPosition: 'after',
    phonePrefix: '+237',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Yaoundé', 'Douala', 'Garoua', 'Other'],
    timezone: 'Africa/Douala',
    enabled: true,
  },
  cd: {
    code: 'CD',
    name: 'DR Congo',
    flag: '🇨🇩',
    currency: 'CDF',
    currencySymbol: 'FC',
    currencyPosition: 'after',
    phonePrefix: '+243',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Kinshasa', 'Lubumbashi', 'Goma', 'Other'],
    timezone: 'Africa/Kinshasa',
    enabled: true,
  },
  ao: {
    code: 'AO',
    name: 'Angola',
    flag: '🇦🇴',
    currency: 'AOA',
    currencySymbol: 'Kz',
    currencyPosition: 'after',
    phonePrefix: '+244',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Luanda', 'Huambo', 'Benguela', 'Other'],
    timezone: 'Africa/Luanda',
    enabled: true,
  },
  mz: {
    code: 'MZ',
    name: 'Mozambique',
    flag: '🇲🇿',
    currency: 'MZN',
    currencySymbol: 'MT',
    currencyPosition: 'after',
    phonePrefix: '+258',
    phoneLength: 9,
    paymentMethods: ['mpesa', 'stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Maputo', 'Beira', 'Nampula', 'Other'],
    timezone: 'Africa/Maputo',
    enabled: true,
  },
  mg: {
    code: 'MG',
    name: 'Madagascar',
    flag: '🇲🇬',
    currency: 'MGA',
    currencySymbol: 'Ar',
    currencyPosition: 'after',
    phonePrefix: '+261',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Antananarivo', 'Toamasina', 'Other'],
    timezone: 'Indian/Antananarivo',
    enabled: true,
  },
  zm: {
    code: 'ZM',
    name: 'Zambia',
    flag: '🇿🇲',
    currency: 'ZMW',
    currencySymbol: 'ZK',
    currencyPosition: 'before',
    phonePrefix: '+260',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Lusaka', 'Kitwe', 'Ndola', 'Other'],
    timezone: 'Africa/Lusaka',
    enabled: true,
  },
  bw: {
    code: 'BW',
    name: 'Botswana',
    flag: '🇧🇼',
    currency: 'BWP',
    currencySymbol: 'P',
    currencyPosition: 'before',
    phonePrefix: '+267',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Gaborone', 'Francistown', 'Other'],
    timezone: 'Africa/Gaborone',
    enabled: true,
  },
  na: {
    code: 'NA',
    name: 'Namibia',
    flag: '🇳🇦',
    currency: 'NAD',
    currencySymbol: 'N$',
    currencyPosition: 'before',
    phonePrefix: '+264',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Windhoek', 'Walvis Bay', 'Other'],
    timezone: 'Africa/Windhoek',
    enabled: true,
  },
  rw: {
    code: 'RW',
    name: 'Rwanda',
    flag: '🇷🇼',
    currency: 'RWF',
    currencySymbol: 'FRw',
    currencyPosition: 'after',
    phonePrefix: '+250',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Kigali', 'Other'],
    timezone: 'Africa/Kigali',
    enabled: true,
  },
  mu: {
    code: 'MU',
    name: 'Mauritius',
    flag: '🇲🇺',
    currency: 'MUR',
    currencySymbol: '₨',
    currencyPosition: 'before',
    phonePrefix: '+230',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Port Louis', 'Other'],
    timezone: 'Indian/Mauritius',
    enabled: true,
  },
  // ============ ADDITIONAL EUROPEAN COUNTRIES ============
  pt: {
    code: 'PT',
    name: 'Portugal',
    flag: '🇵🇹',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+351',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Lisbon', 'Porto', 'Algarve', 'Other'],
    timezone: 'Europe/Lisbon',
    enabled: true,
  },
  be: {
    code: 'BE',
    name: 'Belgium',
    flag: '🇧🇪',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+32',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Brussels', 'Flanders', 'Wallonia', 'Other'],
    timezone: 'Europe/Brussels',
    enabled: true,
  },
  ch: {
    code: 'CH',
    name: 'Switzerland',
    flag: '🇨🇭',
    currency: 'CHF',
    currencySymbol: 'CHF',
    currencyPosition: 'before',
    phonePrefix: '+41',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Zürich', 'Geneva', 'Basel', 'Bern', 'Other'],
    timezone: 'Europe/Zurich',
    enabled: true,
  },
  at: {
    code: 'AT',
    name: 'Austria',
    flag: '🇦🇹',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+43',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Vienna', 'Salzburg', 'Tyrol', 'Other'],
    timezone: 'Europe/Vienna',
    enabled: true,
  },
  pl: {
    code: 'PL',
    name: 'Poland',
    flag: '🇵🇱',
    currency: 'PLN',
    currencySymbol: 'zł',
    currencyPosition: 'after',
    phonePrefix: '+48',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Other'],
    timezone: 'Europe/Warsaw',
    enabled: true,
  },
  cz: {
    code: 'CZ',
    name: 'Czech Republic',
    flag: '🇨🇿',
    currency: 'CZK',
    currencySymbol: 'Kč',
    currencyPosition: 'after',
    phonePrefix: '+420',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Prague', 'Brno', 'Ostrava', 'Other'],
    timezone: 'Europe/Prague',
    enabled: true,
  },
  hu: {
    code: 'HU',
    name: 'Hungary',
    flag: '🇭🇺',
    currency: 'HUF',
    currencySymbol: 'Ft',
    currencyPosition: 'after',
    phonePrefix: '+36',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Budapest', 'Debrecen', 'Szeged', 'Other'],
    timezone: 'Europe/Budapest',
    enabled: true,
  },
  ro: {
    code: 'RO',
    name: 'Romania',
    flag: '🇷🇴',
    currency: 'RON',
    currencySymbol: 'lei',
    currencyPosition: 'after',
    phonePrefix: '+40',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Other'],
    timezone: 'Europe/Bucharest',
    enabled: true,
  },
  bg: {
    code: 'BG',
    name: 'Bulgaria',
    flag: '🇧🇬',
    currency: 'BGN',
    currencySymbol: 'лв',
    currencyPosition: 'after',
    phonePrefix: '+359',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Sofia', 'Plovdiv', 'Varna', 'Other'],
    timezone: 'Europe/Sofia',
    enabled: true,
  },
  gr: {
    code: 'GR',
    name: 'Greece',
    flag: '🇬🇷',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+30',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Athens', 'Thessaloniki', 'Crete', 'Other'],
    timezone: 'Europe/Athens',
    enabled: true,
  },
  hr: {
    code: 'HR',
    name: 'Croatia',
    flag: '🇭🇷',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+385',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Zagreb', 'Split', 'Rijeka', 'Other'],
    timezone: 'Europe/Zagreb',
    enabled: true,
  },
  rs: {
    code: 'RS',
    name: 'Serbia',
    flag: '🇷🇸',
    currency: 'RSD',
    currencySymbol: 'дин',
    currencyPosition: 'after',
    phonePrefix: '+381',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Belgrade', 'Novi Sad', 'Niš', 'Other'],
    timezone: 'Europe/Belgrade',
    enabled: true,
  },
  ua: {
    code: 'UA',
    name: 'Ukraine',
    flag: '🇺🇦',
    currency: 'UAH',
    currencySymbol: '₴',
    currencyPosition: 'after',
    phonePrefix: '+380',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Kyiv', 'Kharkiv', 'Odesa', 'Lviv', 'Other'],
    timezone: 'Europe/Kyiv',
    enabled: true,
  },
  se: {
    code: 'SE',
    name: 'Sweden',
    flag: '🇸🇪',
    currency: 'SEK',
    currencySymbol: 'kr',
    currencyPosition: 'after',
    phonePrefix: '+46',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Stockholm', 'Gothenburg', 'Malmö', 'Other'],
    timezone: 'Europe/Stockholm',
    enabled: true,
  },
  no: {
    code: 'NO',
    name: 'Norway',
    flag: '🇳🇴',
    currency: 'NOK',
    currencySymbol: 'kr',
    currencyPosition: 'after',
    phonePrefix: '+47',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Oslo', 'Bergen', 'Trondheim', 'Other'],
    timezone: 'Europe/Oslo',
    enabled: true,
  },
  dk: {
    code: 'DK',
    name: 'Denmark',
    flag: '🇩🇰',
    currency: 'DKK',
    currencySymbol: 'kr',
    currencyPosition: 'after',
    phonePrefix: '+45',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Copenhagen', 'Aarhus', 'Odense', 'Other'],
    timezone: 'Europe/Copenhagen',
    enabled: true,
  },
  fi: {
    code: 'FI',
    name: 'Finland',
    flag: '🇫🇮',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+358',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Helsinki', 'Tampere', 'Turku', 'Other'],
    timezone: 'Europe/Helsinki',
    enabled: true,
  },
  ru: {
    code: 'RU',
    name: 'Russia',
    flag: '🇷🇺',
    currency: 'RUB',
    currencySymbol: '₽',
    currencyPosition: 'after',
    phonePrefix: '+7',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Other'],
    timezone: 'Europe/Moscow',
    enabled: true,
  },
  // ============ ADDITIONAL ASIAN COUNTRIES ============
  cn: {
    code: 'CN',
    name: 'China',
    flag: '🇨🇳',
    currency: 'CNY',
    currencySymbol: '¥',
    currencyPosition: 'before',
    phonePrefix: '+86',
    phoneLength: 11,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Beijing', 'Shanghai', 'Guangdong', 'Sichuan', 'Other'],
    timezone: 'Asia/Shanghai',
    enabled: true,
  },
  jp: {
    code: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    currency: 'JPY',
    currencySymbol: '¥',
    currencyPosition: 'before',
    phonePrefix: '+81',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Other'],
    timezone: 'Asia/Tokyo',
    enabled: true,
  },
  kr: {
    code: 'KR',
    name: 'South Korea',
    flag: '🇰🇷',
    currency: 'KRW',
    currencySymbol: '₩',
    currencyPosition: 'before',
    phonePrefix: '+82',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Other'],
    timezone: 'Asia/Seoul',
    enabled: true,
  },
  th: {
    code: 'TH',
    name: 'Thailand',
    flag: '🇹🇭',
    currency: 'THB',
    currencySymbol: '฿',
    currencyPosition: 'before',
    phonePrefix: '+66',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Other'],
    timezone: 'Asia/Bangkok',
    enabled: true,
  },
  vn: {
    code: 'VN',
    name: 'Vietnam',
    flag: '🇻🇳',
    currency: 'VND',
    currencySymbol: '₫',
    currencyPosition: 'after',
    phonePrefix: '+84',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Other'],
    timezone: 'Asia/Ho_Chi_Minh',
    enabled: true,
  },
  bd: {
    code: 'BD',
    name: 'Bangladesh',
    flag: '🇧🇩',
    currency: 'BDT',
    currencySymbol: '৳',
    currencyPosition: 'before',
    phonePrefix: '+880',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Dhaka', 'Chittagong', 'Khulna', 'Other'],
    timezone: 'Asia/Dhaka',
    enabled: true,
  },
  lk: {
    code: 'LK',
    name: 'Sri Lanka',
    flag: '🇱🇰',
    currency: 'LKR',
    currencySymbol: 'Rs',
    currencyPosition: 'before',
    phonePrefix: '+94',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Colombo', 'Kandy', 'Galle', 'Other'],
    timezone: 'Asia/Colombo',
    enabled: true,
  },
  np: {
    code: 'NP',
    name: 'Nepal',
    flag: '🇳🇵',
    currency: 'NPR',
    currencySymbol: 'रू',
    currencyPosition: 'before',
    phonePrefix: '+977',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Kathmandu', 'Pokhara', 'Other'],
    timezone: 'Asia/Kathmandu',
    enabled: true,
  },
  mm: {
    code: 'MM',
    name: 'Myanmar',
    flag: '🇲🇲',
    currency: 'MMK',
    currencySymbol: 'K',
    currencyPosition: 'after',
    phonePrefix: '+95',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Yangon', 'Mandalay', 'Other'],
    timezone: 'Asia/Yangon',
    enabled: true,
  },
  kh: {
    code: 'KH',
    name: 'Cambodia',
    flag: '🇰🇭',
    currency: 'KHR',
    currencySymbol: '៛',
    currencyPosition: 'after',
    phonePrefix: '+855',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Phnom Penh', 'Siem Reap', 'Other'],
    timezone: 'Asia/Phnom_Penh',
    enabled: true,
  },
  ir: {
    code: 'IR',
    name: 'Iran',
    flag: '🇮🇷',
    currency: 'IRR',
    currencySymbol: '﷼',
    currencyPosition: 'after',
    phonePrefix: '+98',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Tehran', 'Isfahan', 'Shiraz', 'Other'],
    timezone: 'Asia/Tehran',
    enabled: true,
  },
  iq: {
    code: 'IQ',
    name: 'Iraq',
    flag: '🇮🇶',
    currency: 'IQD',
    currencySymbol: 'ع.د',
    currencyPosition: 'after',
    phonePrefix: '+964',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Baghdad', 'Basra', 'Erbil', 'Other'],
    timezone: 'Asia/Baghdad',
    enabled: true,
  },
  jo: {
    code: 'JO',
    name: 'Jordan',
    flag: '🇯🇴',
    currency: 'JOD',
    currencySymbol: 'د.ا',
    currencyPosition: 'after',
    phonePrefix: '+962',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Amman', 'Irbid', 'Zarqa', 'Other'],
    timezone: 'Asia/Amman',
    enabled: true,
  },
  lb: {
    code: 'LB',
    name: 'Lebanon',
    flag: '🇱🇧',
    currency: 'LBP',
    currencySymbol: 'ل.ل',
    currencyPosition: 'after',
    phonePrefix: '+961',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Beirut', 'Tripoli', 'Other'],
    timezone: 'Asia/Beirut',
    enabled: true,
  },
  kw: {
    code: 'KW',
    name: 'Kuwait',
    flag: '🇰🇼',
    currency: 'KWD',
    currencySymbol: 'د.ك',
    currencyPosition: 'after',
    phonePrefix: '+965',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Kuwait City', 'Other'],
    timezone: 'Asia/Kuwait',
    enabled: true,
  },
  qa: {
    code: 'QA',
    name: 'Qatar',
    flag: '🇶🇦',
    currency: 'QAR',
    currencySymbol: 'ر.ق',
    currencyPosition: 'after',
    phonePrefix: '+974',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Doha', 'Other'],
    timezone: 'Asia/Qatar',
    enabled: true,
  },
  bh: {
    code: 'BH',
    name: 'Bahrain',
    flag: '🇧🇭',
    currency: 'BHD',
    currencySymbol: 'ب.د',
    currencyPosition: 'after',
    phonePrefix: '+973',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Manama', 'Other'],
    timezone: 'Asia/Bahrain',
    enabled: true,
  },
  om: {
    code: 'OM',
    name: 'Oman',
    flag: '🇴🇲',
    currency: 'OMR',
    currencySymbol: 'ر.ع',
    currencyPosition: 'after',
    phonePrefix: '+968',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Muscat', 'Other'],
    timezone: 'Asia/Muscat',
    enabled: true,
  },
  // ============ ADDITIONAL AMERICAN COUNTRIES ============
  cl: {
    code: 'CL',
    name: 'Chile',
    flag: '🇨🇱',
    currency: 'CLP',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+56',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Santiago', 'Valparaíso', 'Concepción', 'Other'],
    timezone: 'America/Santiago',
    enabled: true,
  },
  pe: {
    code: 'PE',
    name: 'Peru',
    flag: '🇵🇪',
    currency: 'PEN',
    currencySymbol: 'S/',
    currencyPosition: 'before',
    phonePrefix: '+51',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Lima', 'Arequipa', 'Cusco', 'Other'],
    timezone: 'America/Lima',
    enabled: true,
  },
  ec: {
    code: 'EC',
    name: 'Ecuador',
    flag: '🇪🇨',
    currency: 'USD',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+593',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Quito', 'Guayaquil', 'Cuenca', 'Other'],
    timezone: 'America/Guayaquil',
    enabled: true,
  },
  ve: {
    code: 'VE',
    name: 'Venezuela',
    flag: '🇻🇪',
    currency: 'VES',
    currencySymbol: 'Bs',
    currencyPosition: 'before',
    phonePrefix: '+58',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Caracas', 'Maracaibo', 'Valencia', 'Other'],
    timezone: 'America/Caracas',
    enabled: true,
  },
  uy: {
    code: 'UY',
    name: 'Uruguay',
    flag: '🇺🇾',
    currency: 'UYU',
    currencySymbol: '$U',
    currencyPosition: 'before',
    phonePrefix: '+598',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Montevideo', 'Other'],
    timezone: 'America/Montevideo',
    enabled: true,
  },
  py: {
    code: 'PY',
    name: 'Paraguay',
    flag: '🇵🇾',
    currency: 'PYG',
    currencySymbol: '₲',
    currencyPosition: 'before',
    phonePrefix: '+595',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Asunción', 'Other'],
    timezone: 'America/Asuncion',
    enabled: true,
  },
  bo: {
    code: 'BO',
    name: 'Bolivia',
    flag: '🇧🇴',
    currency: 'BOB',
    currencySymbol: 'Bs',
    currencyPosition: 'before',
    phonePrefix: '+591',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['La Paz', 'Santa Cruz', 'Cochabamba', 'Other'],
    timezone: 'America/La_Paz',
    enabled: true,
  },
  pa: {
    code: 'PA',
    name: 'Panama',
    flag: '🇵🇦',
    currency: 'PAB',
    currencySymbol: 'B/.',
    currencyPosition: 'before',
    phonePrefix: '+507',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Panama City', 'Other'],
    timezone: 'America/Panama',
    enabled: true,
  },
  cr: {
    code: 'CR',
    name: 'Costa Rica',
    flag: '🇨🇷',
    currency: 'CRC',
    currencySymbol: '₡',
    currencyPosition: 'before',
    phonePrefix: '+506',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['San José', 'Other'],
    timezone: 'America/Costa_Rica',
    enabled: true,
  },
  gt: {
    code: 'GT',
    name: 'Guatemala',
    flag: '🇬🇹',
    currency: 'GTQ',
    currencySymbol: 'Q',
    currencyPosition: 'before',
    phonePrefix: '+502',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Guatemala City', 'Other'],
    timezone: 'America/Guatemala',
    enabled: true,
  },
  hn: {
    code: 'HN',
    name: 'Honduras',
    flag: '🇭🇳',
    currency: 'HNL',
    currencySymbol: 'L',
    currencyPosition: 'before',
    phonePrefix: '+504',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Tegucigalpa', 'San Pedro Sula', 'Other'],
    timezone: 'America/Tegucigalpa',
    enabled: true,
  },
  sv: {
    code: 'SV',
    name: 'El Salvador',
    flag: '🇸🇻',
    currency: 'USD',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+503',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['San Salvador', 'Other'],
    timezone: 'America/El_Salvador',
    enabled: true,
  },
  ni: {
    code: 'NI',
    name: 'Nicaragua',
    flag: '🇳🇮',
    currency: 'NIO',
    currencySymbol: 'C$',
    currencyPosition: 'before',
    phonePrefix: '+505',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Managua', 'Other'],
    timezone: 'America/Managua',
    enabled: true,
  },
  cu: {
    code: 'CU',
    name: 'Cuba',
    flag: '🇨🇺',
    currency: 'CUP',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+53',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Havana', 'Other'],
    timezone: 'America/Havana',
    enabled: true,
  },
  dom: {
    code: 'DO',
    name: 'Dominican Republic',
    flag: '🇩🇴',
    currency: 'DOP',
    currencySymbol: 'RD$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Santo Domingo', 'Santiago', 'Other'],
    timezone: 'America/Santo_Domingo',
    enabled: true,
  },
  pr: {
    code: 'PR',
    name: 'Puerto Rico',
    flag: '🇵🇷',
    currency: 'USD',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['San Juan', 'Other'],
    timezone: 'America/Puerto_Rico',
    enabled: true,
  },
  jm: {
    code: 'JM',
    name: 'Jamaica',
    flag: '🇯🇲',
    currency: 'JMD',
    currencySymbol: 'J$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Kingston', 'Montego Bay', 'Other'],
    timezone: 'America/Jamaica',
    enabled: true,
  },
  tt: {
    code: 'TT',
    name: 'Trinidad and Tobago',
    flag: '🇹🇹',
    currency: 'TTD',
    currencySymbol: 'TT$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Port of Spain', 'Other'],
    timezone: 'America/Port_of_Spain',
    enabled: true,
  },
  // ============ ADDITIONAL OCEANIA COUNTRIES ============
  pg: {
    code: 'PG',
    name: 'Papua New Guinea',
    flag: '🇵🇬',
    currency: 'PGK',
    currencySymbol: 'K',
    currencyPosition: 'before',
    phonePrefix: '+675',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Port Moresby', 'Other'],
    timezone: 'Pacific/Port_Moresby',
    enabled: true,
  },
  fj: {
    code: 'FJ',
    name: 'Fiji',
    flag: '🇫🇯',
    currency: 'FJD',
    currencySymbol: 'FJ$',
    currencyPosition: 'before',
    phonePrefix: '+679',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Suva', 'Other'],
    timezone: 'Pacific/Fiji',
    enabled: true,
  },
  // ============ REMAINING AFRICAN COUNTRIES ============
  ml: {
    code: 'ML',
    name: 'Mali',
    flag: '🇲🇱',
    currency: 'XOF',
    currencySymbol: 'CFA',
    currencyPosition: 'after',
    phonePrefix: '+223',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Bamako', 'Other'],
    timezone: 'Africa/Bamako',
    enabled: true,
  },
  bf: {
    code: 'BF',
    name: 'Burkina Faso',
    flag: '🇧🇫',
    currency: 'XOF',
    currencySymbol: 'CFA',
    currencyPosition: 'after',
    phonePrefix: '+226',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Ouagadougou', 'Other'],
    timezone: 'Africa/Ouagadougou',
    enabled: true,
  },
  ne: {
    code: 'NE',
    name: 'Niger',
    flag: '🇳🇪',
    currency: 'XOF',
    currencySymbol: 'CFA',
    currencyPosition: 'after',
    phonePrefix: '+227',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Niamey', 'Other'],
    timezone: 'Africa/Niamey',
    enabled: true,
  },
  td: {
    code: 'TD',
    name: 'Chad',
    flag: '🇹🇩',
    currency: 'XAF',
    currencySymbol: 'FCFA',
    currencyPosition: 'after',
    phonePrefix: '+235',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ["N'Djamena", 'Other'],
    timezone: 'Africa/Ndjamena',
    enabled: true,
  },
  gn: {
    code: 'GN',
    name: 'Guinea',
    flag: '🇬🇳',
    currency: 'GNF',
    currencySymbol: 'FG',
    currencyPosition: 'after',
    phonePrefix: '+224',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Conakry', 'Other'],
    timezone: 'Africa/Conakry',
    enabled: true,
  },
  bj: {
    code: 'BJ',
    name: 'Benin',
    flag: '🇧🇯',
    currency: 'XOF',
    currencySymbol: 'CFA',
    currencyPosition: 'after',
    phonePrefix: '+229',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Cotonou', 'Porto-Novo', 'Other'],
    timezone: 'Africa/Porto-Novo',
    enabled: true,
  },
  tg: {
    code: 'TG',
    name: 'Togo',
    flag: '🇹🇬',
    currency: 'XOF',
    currencySymbol: 'CFA',
    currencyPosition: 'after',
    phonePrefix: '+228',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Lomé', 'Other'],
    timezone: 'Africa/Lome',
    enabled: true,
  },
  sl: {
    code: 'SL',
    name: 'Sierra Leone',
    flag: '🇸🇱',
    currency: 'SLL',
    currencySymbol: 'Le',
    currencyPosition: 'before',
    phonePrefix: '+232',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Freetown', 'Other'],
    timezone: 'Africa/Freetown',
    enabled: true,
  },
  lr: {
    code: 'LR',
    name: 'Liberia',
    flag: '🇱🇷',
    currency: 'LRD',
    currencySymbol: 'L$',
    currencyPosition: 'before',
    phonePrefix: '+231',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Monrovia', 'Other'],
    timezone: 'Africa/Monrovia',
    enabled: true,
  },
  mr: {
    code: 'MR',
    name: 'Mauritania',
    flag: '🇲🇷',
    currency: 'MRU',
    currencySymbol: 'UM',
    currencyPosition: 'after',
    phonePrefix: '+222',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Nouakchott', 'Other'],
    timezone: 'Africa/Nouakchott',
    enabled: true,
  },
  gm: {
    code: 'GM',
    name: 'Gambia',
    flag: '🇬🇲',
    currency: 'GMD',
    currencySymbol: 'D',
    currencyPosition: 'before',
    phonePrefix: '+220',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Banjul', 'Other'],
    timezone: 'Africa/Banjul',
    enabled: true,
  },
  ga: {
    code: 'GA',
    name: 'Gabon',
    flag: '🇬🇦',
    currency: 'XAF',
    currencySymbol: 'FCFA',
    currencyPosition: 'after',
    phonePrefix: '+241',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Libreville', 'Other'],
    timezone: 'Africa/Libreville',
    enabled: true,
  },
  cg: {
    code: 'CG',
    name: 'Republic of Congo',
    flag: '🇨🇬',
    currency: 'XAF',
    currencySymbol: 'FCFA',
    currencyPosition: 'after',
    phonePrefix: '+242',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Brazzaville', 'Pointe-Noire', 'Other'],
    timezone: 'Africa/Brazzaville',
    enabled: true,
  },
  bi: {
    code: 'BI',
    name: 'Burundi',
    flag: '🇧🇮',
    currency: 'BIF',
    currencySymbol: 'FBu',
    currencyPosition: 'after',
    phonePrefix: '+257',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Bujumbura', 'Other'],
    timezone: 'Africa/Bujumbura',
    enabled: true,
  },
  mw: {
    code: 'MW',
    name: 'Malawi',
    flag: '🇲🇼',
    currency: 'MWK',
    currencySymbol: 'MK',
    currencyPosition: 'before',
    phonePrefix: '+265',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Lilongwe', 'Blantyre', 'Other'],
    timezone: 'Africa/Blantyre',
    enabled: true,
  },
  sz: {
    code: 'SZ',
    name: 'Eswatini',
    flag: '🇸🇿',
    currency: 'SZL',
    currencySymbol: 'E',
    currencyPosition: 'before',
    phonePrefix: '+268',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Mbabane', 'Other'],
    timezone: 'Africa/Mbabane',
    enabled: true,
  },
  ls: {
    code: 'LS',
    name: 'Lesotho',
    flag: '🇱🇸',
    currency: 'LSL',
    currencySymbol: 'L',
    currencyPosition: 'before',
    phonePrefix: '+266',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Maseru', 'Other'],
    timezone: 'Africa/Maseru',
    enabled: true,
  },
  so: {
    code: 'SO',
    name: 'Somalia',
    flag: '🇸🇴',
    currency: 'SOS',
    currencySymbol: 'Sh',
    currencyPosition: 'before',
    phonePrefix: '+252',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Mogadishu', 'Other'],
    timezone: 'Africa/Mogadishu',
    enabled: true,
  },
  dj: {
    code: 'DJ',
    name: 'Djibouti',
    flag: '🇩🇯',
    currency: 'DJF',
    currencySymbol: 'Fdj',
    currencyPosition: 'after',
    phonePrefix: '+253',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Djibouti City', 'Other'],
    timezone: 'Africa/Djibouti',
    enabled: true,
  },
  er: {
    code: 'ER',
    name: 'Eritrea',
    flag: '🇪🇷',
    currency: 'ERN',
    currencySymbol: 'Nfk',
    currencyPosition: 'before',
    phonePrefix: '+291',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Asmara', 'Other'],
    timezone: 'Africa/Asmara',
    enabled: true,
  },
  cv: {
    code: 'CV',
    name: 'Cape Verde',
    flag: '🇨🇻',
    currency: 'CVE',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+238',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Praia', 'Other'],
    timezone: 'Atlantic/Cape_Verde',
    enabled: true,
  },
  sc: {
    code: 'SC',
    name: 'Seychelles',
    flag: '🇸🇨',
    currency: 'SCR',
    currencySymbol: '₨',
    currencyPosition: 'before',
    phonePrefix: '+248',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Victoria', 'Other'],
    timezone: 'Indian/Mahe',
    enabled: true,
  },
  // ============ REMAINING EUROPEAN COUNTRIES ============
  sk: {
    code: 'SK',
    name: 'Slovakia',
    flag: '🇸🇰',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+421',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Bratislava', 'Košice', 'Other'],
    timezone: 'Europe/Bratislava',
    enabled: true,
  },
  si: {
    code: 'SI',
    name: 'Slovenia',
    flag: '🇸🇮',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+386',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Ljubljana', 'Maribor', 'Other'],
    timezone: 'Europe/Ljubljana',
    enabled: true,
  },
  ee: {
    code: 'EE',
    name: 'Estonia',
    flag: '🇪🇪',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+372',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Tallinn', 'Tartu', 'Other'],
    timezone: 'Europe/Tallinn',
    enabled: true,
  },
  lv: {
    code: 'LV',
    name: 'Latvia',
    flag: '🇱🇻',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+371',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Riga', 'Other'],
    timezone: 'Europe/Riga',
    enabled: true,
  },
  lt: {
    code: 'LT',
    name: 'Lithuania',
    flag: '🇱🇹',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+370',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Vilnius', 'Kaunas', 'Other'],
    timezone: 'Europe/Vilnius',
    enabled: true,
  },
  ba: {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
    currency: 'BAM',
    currencySymbol: 'KM',
    currencyPosition: 'after',
    phonePrefix: '+387',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Sarajevo', 'Other'],
    timezone: 'Europe/Sarajevo',
    enabled: true,
  },
  mk: {
    code: 'MK',
    name: 'North Macedonia',
    flag: '🇲🇰',
    currency: 'MKD',
    currencySymbol: 'ден',
    currencyPosition: 'after',
    phonePrefix: '+389',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Skopje', 'Other'],
    timezone: 'Europe/Skopje',
    enabled: true,
  },
  al: {
    code: 'AL',
    name: 'Albania',
    flag: '🇦🇱',
    currency: 'ALL',
    currencySymbol: 'L',
    currencyPosition: 'after',
    phonePrefix: '+355',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Tirana', 'Other'],
    timezone: 'Europe/Tirane',
    enabled: true,
  },
  me: {
    code: 'ME',
    name: 'Montenegro',
    flag: '🇲🇪',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+382',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Podgorica', 'Other'],
    timezone: 'Europe/Podgorica',
    enabled: true,
  },
  xk: {
    code: 'XK',
    name: 'Kosovo',
    flag: '🇽🇰',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+383',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Pristina', 'Other'],
    timezone: 'Europe/Belgrade',
    enabled: true,
  },
  md: {
    code: 'MD',
    name: 'Moldova',
    flag: '🇲🇩',
    currency: 'MDL',
    currencySymbol: 'L',
    currencyPosition: 'after',
    phonePrefix: '+373',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Chișinău', 'Other'],
    timezone: 'Europe/Chisinau',
    enabled: true,
  },
  by: {
    code: 'BY',
    name: 'Belarus',
    flag: '🇧🇾',
    currency: 'BYN',
    currencySymbol: 'Br',
    currencyPosition: 'after',
    phonePrefix: '+375',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Minsk', 'Other'],
    timezone: 'Europe/Minsk',
    enabled: true,
  },
  is: {
    code: 'IS',
    name: 'Iceland',
    flag: '🇮🇸',
    currency: 'ISK',
    currencySymbol: 'kr',
    currencyPosition: 'after',
    phonePrefix: '+354',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Reykjavik', 'Other'],
    timezone: 'Atlantic/Reykjavik',
    enabled: true,
  },
  lu: {
    code: 'LU',
    name: 'Luxembourg',
    flag: '🇱🇺',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+352',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Luxembourg City', 'Other'],
    timezone: 'Europe/Luxembourg',
    enabled: true,
  },
  mt: {
    code: 'MT',
    name: 'Malta',
    flag: '🇲🇹',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+356',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Valletta', 'Other'],
    timezone: 'Europe/Malta',
    enabled: true,
  },
  cyp: {
    code: 'CY',
    name: 'Cyprus',
    flag: '🇨🇾',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+357',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Nicosia', 'Limassol', 'Other'],
    timezone: 'Asia/Nicosia',
    enabled: true,
  },
  // ============ REMAINING ASIAN COUNTRIES ============
  af: {
    code: 'AF',
    name: 'Afghanistan',
    flag: '🇦🇫',
    currency: 'AFN',
    currencySymbol: '؋',
    currencyPosition: 'after',
    phonePrefix: '+93',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Kabul', 'Kandahar', 'Herat', 'Other'],
    timezone: 'Asia/Kabul',
    enabled: true,
  },
  kz: {
    code: 'KZ',
    name: 'Kazakhstan',
    flag: '🇰🇿',
    currency: 'KZT',
    currencySymbol: '₸',
    currencyPosition: 'after',
    phonePrefix: '+7',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Almaty', 'Astana', 'Other'],
    timezone: 'Asia/Almaty',
    enabled: true,
  },
  uz: {
    code: 'UZ',
    name: 'Uzbekistan',
    flag: '🇺🇿',
    currency: 'UZS',
    currencySymbol: 'soʻm',
    currencyPosition: 'after',
    phonePrefix: '+998',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Tashkent', 'Samarkand', 'Other'],
    timezone: 'Asia/Tashkent',
    enabled: true,
  },
  tm: {
    code: 'TM',
    name: 'Turkmenistan',
    flag: '🇹🇲',
    currency: 'TMT',
    currencySymbol: 'm',
    currencyPosition: 'after',
    phonePrefix: '+993',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Ashgabat', 'Other'],
    timezone: 'Asia/Ashgabat',
    enabled: true,
  },
  tj: {
    code: 'TJ',
    name: 'Tajikistan',
    flag: '🇹🇯',
    currency: 'TJS',
    currencySymbol: 'SM',
    currencyPosition: 'after',
    phonePrefix: '+992',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Dushanbe', 'Other'],
    timezone: 'Asia/Dushanbe',
    enabled: true,
  },
  kg: {
    code: 'KG',
    name: 'Kyrgyzstan',
    flag: '🇰🇬',
    currency: 'KGS',
    currencySymbol: 'сом',
    currencyPosition: 'after',
    phonePrefix: '+996',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Bishkek', 'Other'],
    timezone: 'Asia/Bishkek',
    enabled: true,
  },
  mn: {
    code: 'MN',
    name: 'Mongolia',
    flag: '🇲🇳',
    currency: 'MNT',
    currencySymbol: '₮',
    currencyPosition: 'after',
    phonePrefix: '+976',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Ulaanbaatar', 'Other'],
    timezone: 'Asia/Ulaanbaatar',
    enabled: true,
  },
  az: {
    code: 'AZ',
    name: 'Azerbaijan',
    flag: '🇦🇿',
    currency: 'AZN',
    currencySymbol: '₼',
    currencyPosition: 'after',
    phonePrefix: '+994',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Baku', 'Other'],
    timezone: 'Asia/Baku',
    enabled: true,
  },
  geo: {
    code: 'GE',
    name: 'Georgia',
    flag: '🇬🇪',
    currency: 'GEL',
    currencySymbol: '₾',
    currencyPosition: 'after',
    phonePrefix: '+995',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Tbilisi', 'Other'],
    timezone: 'Asia/Tbilisi',
    enabled: true,
  },
  am: {
    code: 'AM',
    name: 'Armenia',
    flag: '🇦🇲',
    currency: 'AMD',
    currencySymbol: '֏',
    currencyPosition: 'after',
    phonePrefix: '+374',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Yerevan', 'Other'],
    timezone: 'Asia/Yerevan',
    enabled: true,
  },
  sy: {
    code: 'SY',
    name: 'Syria',
    flag: '🇸🇾',
    currency: 'SYP',
    currencySymbol: '£S',
    currencyPosition: 'after',
    phonePrefix: '+963',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Damascus', 'Aleppo', 'Other'],
    timezone: 'Asia/Damascus',
    enabled: true,
  },
  ye: {
    code: 'YE',
    name: 'Yemen',
    flag: '🇾🇪',
    currency: 'YER',
    currencySymbol: '﷼',
    currencyPosition: 'after',
    phonePrefix: '+967',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ["Sana'a", 'Aden', 'Other'],
    timezone: 'Asia/Aden',
    enabled: true,
  },
  la: {
    code: 'LA',
    name: 'Laos',
    flag: '🇱🇦',
    currency: 'LAK',
    currencySymbol: '₭',
    currencyPosition: 'after',
    phonePrefix: '+856',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Vientiane', 'Other'],
    timezone: 'Asia/Vientiane',
    enabled: true,
  },
  bt: {
    code: 'BT',
    name: 'Bhutan',
    flag: '🇧🇹',
    currency: 'BTN',
    currencySymbol: 'Nu.',
    currencyPosition: 'before',
    phonePrefix: '+975',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Thimphu', 'Other'],
    timezone: 'Asia/Thimphu',
    enabled: true,
  },
  mv: {
    code: 'MV',
    name: 'Maldives',
    flag: '🇲🇻',
    currency: 'MVR',
    currencySymbol: 'Rf',
    currencyPosition: 'before',
    phonePrefix: '+960',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Malé', 'Other'],
    timezone: 'Indian/Maldives',
    enabled: true,
  },
  bn: {
    code: 'BN',
    name: 'Brunei',
    flag: '🇧🇳',
    currency: 'BND',
    currencySymbol: 'B$',
    currencyPosition: 'before',
    phonePrefix: '+673',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Bandar Seri Begawan', 'Other'],
    timezone: 'Asia/Brunei',
    enabled: true,
  },
  tl: {
    code: 'TL',
    name: 'Timor-Leste',
    flag: '🇹🇱',
    currency: 'USD',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+670',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Dili', 'Other'],
    timezone: 'Asia/Dili',
    enabled: true,
  },
  // ============ REMAINING AMERICAN COUNTRIES ============
  gy: {
    code: 'GY',
    name: 'Guyana',
    flag: '🇬🇾',
    currency: 'GYD',
    currencySymbol: 'G$',
    currencyPosition: 'before',
    phonePrefix: '+592',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Georgetown', 'Other'],
    timezone: 'America/Guyana',
    enabled: true,
  },
  sr: {
    code: 'SR',
    name: 'Suriname',
    flag: '🇸🇷',
    currency: 'SRD',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+597',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Paramaribo', 'Other'],
    timezone: 'America/Paramaribo',
    enabled: true,
  },
  bz: {
    code: 'BZ',
    name: 'Belize',
    flag: '🇧🇿',
    currency: 'BZD',
    currencySymbol: 'BZ$',
    currencyPosition: 'before',
    phonePrefix: '+501',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Belize City', 'Belmopan', 'Other'],
    timezone: 'America/Belize',
    enabled: true,
  },
  ht: {
    code: 'HT',
    name: 'Haiti',
    flag: '🇭🇹',
    currency: 'HTG',
    currencySymbol: 'G',
    currencyPosition: 'before',
    phonePrefix: '+509',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Port-au-Prince', 'Other'],
    timezone: 'America/Port-au-Prince',
    enabled: true,
  },
  bs: {
    code: 'BS',
    name: 'Bahamas',
    flag: '🇧🇸',
    currency: 'BSD',
    currencySymbol: 'B$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Nassau', 'Other'],
    timezone: 'America/Nassau',
    enabled: true,
  },
  bb: {
    code: 'BB',
    name: 'Barbados',
    flag: '🇧🇧',
    currency: 'BBD',
    currencySymbol: 'Bds$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Bridgetown', 'Other'],
    timezone: 'America/Barbados',
    enabled: true,
  },
  // ============ REMAINING OCEANIA COUNTRIES ============
  ws: {
    code: 'WS',
    name: 'Samoa',
    flag: '🇼🇸',
    currency: 'WST',
    currencySymbol: 'WS$',
    currencyPosition: 'before',
    phonePrefix: '+685',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Apia', 'Other'],
    timezone: 'Pacific/Apia',
    enabled: true,
  },
  to: {
    code: 'TO',
    name: 'Tonga',
    flag: '🇹🇴',
    currency: 'TOP',
    currencySymbol: 'T$',
    currencyPosition: 'before',
    phonePrefix: '+676',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ["Nuku'alofa", 'Other'],
    timezone: 'Pacific/Tongatapu',
    enabled: true,
  },
  vu: {
    code: 'VU',
    name: 'Vanuatu',
    flag: '🇻🇺',
    currency: 'VUV',
    currencySymbol: 'VT',
    currencyPosition: 'after',
    phonePrefix: '+678',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Port Vila', 'Other'],
    timezone: 'Pacific/Efate',
    enabled: true,
  },
  sb: {
    code: 'SB',
    name: 'Solomon Islands',
    flag: '🇸🇧',
    currency: 'SBD',
    currencySymbol: 'SI$',
    currencyPosition: 'before',
    phonePrefix: '+677',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Honiara', 'Other'],
    timezone: 'Pacific/Guadalcanal',
    enabled: true,
  },
}

// Get enabled countries only
export function getEnabledCountries(): Record<string, CountryConfig> {
  return Object.fromEntries(
    Object.entries(countries).filter(([, config]) => config.enabled)
  )
}

// Get all country codes
export function getCountryCodes(): string[] {
  return Object.keys(countries)
}

// Get enabled country codes
export function getEnabledCountryCodes(): string[] {
  return Object.keys(getEnabledCountries())
}

// Check if a country code is valid
export function isValidCountry(code: string): boolean {
  return code in countries
}

// Check if a country is enabled
export function isCountryEnabled(code: string): boolean {
  return countries[code]?.enabled ?? false
}

// Get country config by code
export function getCountryConfig(code: string): CountryConfig | null {
  return countries[code] || null
}

// Format price for a country
export function formatPrice(cents: number, countryCode: string): string {
  const config = countries[countryCode]
  if (!config) return `${cents / 100}`

  const amount = (cents / 100).toFixed(2)
  return config.currencyPosition === 'before'
    ? `${config.currencySymbol}${amount}`
    : `${amount}${config.currencySymbol}`
}

// Validate phone number for a country
export function isValidPhoneForCountry(phone: string, countryCode: string): boolean {
  const config = countries[countryCode]
  if (!config) return false

  // Remove all non-digits
  const digits = phone.replace(/\D/g, '')

  // Check if starts with country code (without +)
  const prefix = config.phonePrefix.replace('+', '')

  if (digits.startsWith(prefix)) {
    // International format: +27821234567
    return digits.length === prefix.length + config.phoneLength
  } else if (digits.startsWith('0')) {
    // Local format: 0821234567
    return digits.length === config.phoneLength + 1
  } else {
    // Just the number: 821234567
    return digits.length === config.phoneLength
  }
}

// Format phone to international format
export function formatPhoneForCountry(phone: string, countryCode: string): string {
  const config = countries[countryCode]
  if (!config) return phone

  // Remove all non-digits
  let digits = phone.replace(/\D/g, '')

  // Remove leading zero
  if (digits.startsWith('0')) {
    digits = digits.substring(1)
  }

  // Remove country code if present
  const prefix = config.phonePrefix.replace('+', '')
  if (digits.startsWith(prefix)) {
    digits = digits.substring(prefix.length)
  }

  return `${config.phonePrefix}${digits}`
}

// Default country (for redirects)
export const DEFAULT_COUNTRY = 'sa'
