/**
 * Multi-Country Configuration
 *
 * Each country has its own:
 * - Currency and pricing
 * - Phone validation
 * - Payment methods
 * - Categories
 * - Localized content
 */

export interface CountryConfig {
  code: string // ISO 3166-1 alpha-2
  name: string
  flag: string // emoji
  currency: string
  currencySymbol: string
  currencyPosition: 'before' | 'after'
  phonePrefix: string
  phoneLength: number // digits after country code
  paymentMethods: ('carrier' | 'payfast' | 'paystack' | 'stripe' | 'mpesa' | 'flutterwave')[]
  categories: string[]
  provinces?: string[] // states/provinces/regions
  timezone: string
  enabled: boolean
}

export const countries: Record<string, CountryConfig> = {
  sa: {
    code: 'ZA',
    name: 'South Africa',
    flag: '🇿🇦',
    currency: 'ZAR',
    currencySymbol: 'R',
    currencyPosition: 'before',
    phonePrefix: '+27',
    phoneLength: 9,
    paymentMethods: ['carrier', 'payfast'],
    categories: [
      'BREAKING',
      'TRAFFIC',
      'CRIME',
      'PROTEST',
      'LOADSHEDDING',
      'WEATHER',
      'COMMUNITY',
      'POLITICS',
      'OTHER',
    ],
    provinces: [
      'Gauteng',
      'Western Cape',
      'KwaZulu-Natal',
      'Eastern Cape',
      'Free State',
      'Limpopo',
      'Mpumalanga',
      'North West',
      'Northern Cape',
    ],
    timezone: 'Africa/Johannesburg',
    enabled: true,
  },
  ng: {
    code: 'NG',
    name: 'Nigeria',
    flag: '🇳🇬',
    currency: 'NGN',
    currencySymbol: '₦',
    currencyPosition: 'before',
    phonePrefix: '+234',
    phoneLength: 10,
    paymentMethods: ['paystack', 'flutterwave'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'FUEL_SCARCITY',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Lagos',
      'Abuja',
      'Rivers',
      'Kano',
      'Oyo',
      'Kaduna',
      'Delta',
      'Anambra',
      'Other',
    ],
    timezone: 'Africa/Lagos',
    enabled: true,
  },
  ke: {
    code: 'KE',
    name: 'Kenya',
    flag: '🇰🇪',
    currency: 'KES',
    currencySymbol: 'KSh',
    currencyPosition: 'before',
    phonePrefix: '+254',
    phoneLength: 9,
    paymentMethods: ['mpesa', 'stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Nairobi',
      'Mombasa',
      'Kisumu',
      'Nakuru',
      'Eldoret',
      'Other',
    ],
    timezone: 'Africa/Nairobi',
    enabled: true,
  },
  gh: {
    code: 'GH',
    name: 'Ghana',
    flag: '🇬🇭',
    currency: 'GHS',
    currencySymbol: 'GH₵',
    currencyPosition: 'before',
    phonePrefix: '+233',
    phoneLength: 9,
    paymentMethods: ['flutterwave', 'stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Greater Accra',
      'Ashanti',
      'Central',
      'Western',
      'Eastern',
      'Other',
    ],
    timezone: 'Africa/Accra',
    enabled: true,
  },
  us: {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    currency: 'USD',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [], // Too many states to list
    timezone: 'America/New_York',
    enabled: true,
  },
  uk: {
    code: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    currency: 'GBP',
    currencySymbol: '£',
    currencyPosition: 'before',
    phonePrefix: '+44',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'England',
      'Scotland',
      'Wales',
      'Northern Ireland',
    ],
    timezone: 'Europe/London',
    enabled: true,
  },
  // Africa
  zw: {
    code: 'ZW',
    name: 'Zimbabwe',
    flag: '🇿🇼',
    currency: 'USD',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+263',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Harare',
      'Bulawayo',
      'Manicaland',
      'Mashonaland',
      'Matabeleland',
      'Midlands',
      'Masvingo',
      'Other',
    ],
    timezone: 'Africa/Harare',
    enabled: true,
  },
  eg: {
    code: 'EG',
    name: 'Egypt',
    flag: '🇪🇬',
    currency: 'EGP',
    currencySymbol: 'E£',
    currencyPosition: 'before',
    phonePrefix: '+20',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Cairo',
      'Alexandria',
      'Giza',
      'Luxor',
      'Aswan',
      'Other',
    ],
    timezone: 'Africa/Cairo',
    enabled: true,
  },
  ma: {
    code: 'MA',
    name: 'Morocco',
    flag: '🇲🇦',
    currency: 'MAD',
    currencySymbol: 'MAD',
    currencyPosition: 'after',
    phonePrefix: '+212',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Casablanca',
      'Rabat',
      'Marrakech',
      'Fes',
      'Tangier',
      'Other',
    ],
    timezone: 'Africa/Casablanca',
    enabled: true,
  },
  tz: {
    code: 'TZ',
    name: 'Tanzania',
    flag: '🇹🇿',
    currency: 'TZS',
    currencySymbol: 'TSh',
    currencyPosition: 'before',
    phonePrefix: '+255',
    phoneLength: 9,
    paymentMethods: ['mpesa', 'stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Dar es Salaam',
      'Dodoma',
      'Arusha',
      'Mwanza',
      'Zanzibar',
      'Other',
    ],
    timezone: 'Africa/Dar_es_Salaam',
    enabled: true,
  },
  ug: {
    code: 'UG',
    name: 'Uganda',
    flag: '🇺🇬',
    currency: 'UGX',
    currencySymbol: 'USh',
    currencyPosition: 'before',
    phonePrefix: '+256',
    phoneLength: 9,
    paymentMethods: ['mpesa', 'stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Kampala',
      'Entebbe',
      'Jinja',
      'Gulu',
      'Mbarara',
      'Other',
    ],
    timezone: 'Africa/Kampala',
    enabled: true,
  },
  et: {
    code: 'ET',
    name: 'Ethiopia',
    flag: '🇪🇹',
    currency: 'ETB',
    currencySymbol: 'Br',
    currencyPosition: 'before',
    phonePrefix: '+251',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Addis Ababa',
      'Dire Dawa',
      'Oromia',
      'Amhara',
      'Tigray',
      'Other',
    ],
    timezone: 'Africa/Addis_Ababa',
    enabled: true,
  },
  // Europe
  de: {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+49',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Berlin',
      'Bavaria',
      'Hamburg',
      'North Rhine-Westphalia',
      'Baden-Württemberg',
      'Other',
    ],
    timezone: 'Europe/Berlin',
    enabled: true,
  },
  fr: {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+33',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Île-de-France',
      'Provence-Alpes-Côte d\'Azur',
      'Auvergne-Rhône-Alpes',
      'Nouvelle-Aquitaine',
      'Occitanie',
      'Other',
    ],
    timezone: 'Europe/Paris',
    enabled: true,
  },
  es: {
    code: 'ES',
    name: 'Spain',
    flag: '🇪🇸',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+34',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Madrid',
      'Catalonia',
      'Andalusia',
      'Valencia',
      'Basque Country',
      'Other',
    ],
    timezone: 'Europe/Madrid',
    enabled: true,
  },
  it: {
    code: 'IT',
    name: 'Italy',
    flag: '🇮🇹',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+39',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Lombardy',
      'Lazio',
      'Campania',
      'Sicily',
      'Veneto',
      'Other',
    ],
    timezone: 'Europe/Rome',
    enabled: true,
  },
  nl: {
    code: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+31',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'North Holland',
      'South Holland',
      'Utrecht',
      'North Brabant',
      'Gelderland',
      'Other',
    ],
    timezone: 'Europe/Amsterdam',
    enabled: true,
  },
  ie: {
    code: 'IE',
    name: 'Ireland',
    flag: '🇮🇪',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+353',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Dublin',
      'Cork',
      'Galway',
      'Limerick',
      'Waterford',
      'Other',
    ],
    timezone: 'Europe/Dublin',
    enabled: true,
  },
  // Asia
  ind: {
    code: 'IN',
    name: 'India',
    flag: '🇮🇳',
    currency: 'INR',
    currencySymbol: '₹',
    currencyPosition: 'before',
    phonePrefix: '+91',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Maharashtra',
      'Delhi',
      'Karnataka',
      'Tamil Nadu',
      'West Bengal',
      'Other',
    ],
    timezone: 'Asia/Kolkata',
    enabled: true,
  },
  pk: {
    code: 'PK',
    name: 'Pakistan',
    flag: '🇵🇰',
    currency: 'PKR',
    currencySymbol: '₨',
    currencyPosition: 'before',
    phonePrefix: '+92',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Punjab',
      'Sindh',
      'Khyber Pakhtunkhwa',
      'Balochistan',
      'Islamabad',
      'Other',
    ],
    timezone: 'Asia/Karachi',
    enabled: true,
  },
  ph: {
    code: 'PH',
    name: 'Philippines',
    flag: '🇵🇭',
    currency: 'PHP',
    currencySymbol: '₱',
    currencyPosition: 'before',
    phonePrefix: '+63',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Metro Manila',
      'Cebu',
      'Davao',
      'Calabarzon',
      'Central Luzon',
      'Other',
    ],
    timezone: 'Asia/Manila',
    enabled: true,
  },
  idn: {
    code: 'ID',
    name: 'Indonesia',
    flag: '🇮🇩',
    currency: 'IDR',
    currencySymbol: 'Rp',
    currencyPosition: 'before',
    phonePrefix: '+62',
    phoneLength: 11,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Jakarta',
      'West Java',
      'East Java',
      'Central Java',
      'Bali',
      'Other',
    ],
    timezone: 'Asia/Jakarta',
    enabled: true,
  },
  my: {
    code: 'MY',
    name: 'Malaysia',
    flag: '🇲🇾',
    currency: 'MYR',
    currencySymbol: 'RM',
    currencyPosition: 'before',
    phonePrefix: '+60',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Kuala Lumpur',
      'Selangor',
      'Penang',
      'Johor',
      'Sabah',
      'Sarawak',
      'Other',
    ],
    timezone: 'Asia/Kuala_Lumpur',
    enabled: true,
  },
  sg: {
    code: 'SG',
    name: 'Singapore',
    flag: '🇸🇬',
    currency: 'SGD',
    currencySymbol: 'S$',
    currencyPosition: 'before',
    phonePrefix: '+65',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [],
    timezone: 'Asia/Singapore',
    enabled: true,
  },
  // Americas
  ca: {
    code: 'CA',
    name: 'Canada',
    flag: '🇨🇦',
    currency: 'CAD',
    currencySymbol: 'C$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Ontario',
      'Quebec',
      'British Columbia',
      'Alberta',
      'Manitoba',
      'Other',
    ],
    timezone: 'America/Toronto',
    enabled: true,
  },
  mx: {
    code: 'MX',
    name: 'Mexico',
    flag: '🇲🇽',
    currency: 'MXN',
    currencySymbol: 'MX$',
    currencyPosition: 'before',
    phonePrefix: '+52',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Mexico City',
      'Jalisco',
      'Nuevo León',
      'Yucatán',
      'Quintana Roo',
      'Other',
    ],
    timezone: 'America/Mexico_City',
    enabled: true,
  },
  br: {
    code: 'BR',
    name: 'Brazil',
    flag: '🇧🇷',
    currency: 'BRL',
    currencySymbol: 'R$',
    currencyPosition: 'before',
    phonePrefix: '+55',
    phoneLength: 11,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'São Paulo',
      'Rio de Janeiro',
      'Minas Gerais',
      'Bahia',
      'Paraná',
      'Other',
    ],
    timezone: 'America/Sao_Paulo',
    enabled: true,
  },
  ar: {
    code: 'AR',
    name: 'Argentina',
    flag: '🇦🇷',
    currency: 'ARS',
    currencySymbol: 'AR$',
    currencyPosition: 'before',
    phonePrefix: '+54',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Buenos Aires',
      'Córdoba',
      'Santa Fe',
      'Mendoza',
      'Tucumán',
      'Other',
    ],
    timezone: 'America/Argentina/Buenos_Aires',
    enabled: true,
  },
  co: {
    code: 'CO',
    name: 'Colombia',
    flag: '🇨🇴',
    currency: 'COP',
    currencySymbol: 'CO$',
    currencyPosition: 'before',
    phonePrefix: '+57',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Bogotá',
      'Antioquia',
      'Valle del Cauca',
      'Atlántico',
      'Santander',
      'Other',
    ],
    timezone: 'America/Bogota',
    enabled: true,
  },
  // Oceania
  au: {
    code: 'AU',
    name: 'Australia',
    flag: '🇦🇺',
    currency: 'AUD',
    currencySymbol: 'A$',
    currencyPosition: 'before',
    phonePrefix: '+61',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'New South Wales',
      'Victoria',
      'Queensland',
      'Western Australia',
      'South Australia',
      'Tasmania',
      'Other',
    ],
    timezone: 'Australia/Sydney',
    enabled: true,
  },
  nz: {
    code: 'NZ',
    name: 'New Zealand',
    flag: '🇳🇿',
    currency: 'NZD',
    currencySymbol: 'NZ$',
    currencyPosition: 'before',
    phonePrefix: '+64',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Auckland',
      'Wellington',
      'Canterbury',
      'Waikato',
      'Otago',
      'Other',
    ],
    timezone: 'Pacific/Auckland',
    enabled: true,
  },
  // Middle East
  ae: {
    code: 'AE',
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    currency: 'AED',
    currencySymbol: 'AED',
    currencyPosition: 'before',
    phonePrefix: '+971',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Dubai',
      'Abu Dhabi',
      'Sharjah',
      'Ajman',
      'Other',
    ],
    timezone: 'Asia/Dubai',
    enabled: true,
  },
  ksa: {
    code: 'SA',
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    currency: 'SAR',
    currencySymbol: 'SAR',
    currencyPosition: 'before',
    phonePrefix: '+966',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Riyadh',
      'Makkah',
      'Eastern Province',
      'Madinah',
      'Other',
    ],
    timezone: 'Asia/Riyadh',
    enabled: true,
  },
  il: {
    code: 'IL',
    name: 'Israel',
    flag: '🇮🇱',
    currency: 'ILS',
    currencySymbol: '₪',
    currencyPosition: 'before',
    phonePrefix: '+972',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: [
      'BREAKING',
      'CRIME',
      'POLITICS',
      'PROTEST',
      'WEATHER',
      'COMMUNITY',
      'OTHER',
    ],
    provinces: [
      'Tel Aviv',
      'Jerusalem',
      'Haifa',
      'Central District',
      'Other',
    ],
    timezone: 'Asia/Jerusalem',
    enabled: true,
  },
  // ============ ADDITIONAL AFRICAN COUNTRIES ============
  dz: {
    code: 'DZ',
    name: 'Algeria',
    flag: '🇩🇿',
    currency: 'DZD',
    currencySymbol: 'د.ج',
    currencyPosition: 'after',
    phonePrefix: '+213',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Other'],
    timezone: 'Africa/Algiers',
    enabled: true,
  },
  tn: {
    code: 'TN',
    name: 'Tunisia',
    flag: '🇹🇳',
    currency: 'TND',
    currencySymbol: 'د.ت',
    currencyPosition: 'after',
    phonePrefix: '+216',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Tunis', 'Sfax', 'Sousse', 'Other'],
    timezone: 'Africa/Tunis',
    enabled: true,
  },
  ly: {
    code: 'LY',
    name: 'Libya',
    flag: '🇱🇾',
    currency: 'LYD',
    currencySymbol: 'ل.د',
    currencyPosition: 'after',
    phonePrefix: '+218',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Tripoli', 'Benghazi', 'Misrata', 'Other'],
    timezone: 'Africa/Tripoli',
    enabled: true,
  },
  sd: {
    code: 'SD',
    name: 'Sudan',
    flag: '🇸🇩',
    currency: 'SDG',
    currencySymbol: 'ج.س',
    currencyPosition: 'after',
    phonePrefix: '+249',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Khartoum', 'Omdurman', 'Port Sudan', 'Other'],
    timezone: 'Africa/Khartoum',
    enabled: true,
  },
  ss: {
    code: 'SS',
    name: 'South Sudan',
    flag: '🇸🇸',
    currency: 'SSP',
    currencySymbol: '£',
    currencyPosition: 'before',
    phonePrefix: '+211',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Juba', 'Other'],
    timezone: 'Africa/Juba',
    enabled: true,
  },
  sn: {
    code: 'SN',
    name: 'Senegal',
    flag: '🇸🇳',
    currency: 'XOF',
    currencySymbol: 'CFA',
    currencyPosition: 'after',
    phonePrefix: '+221',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Dakar', 'Thiès', 'Saint-Louis', 'Other'],
    timezone: 'Africa/Dakar',
    enabled: true,
  },
  ci: {
    code: 'CI',
    name: 'Côte d\'Ivoire',
    flag: '🇨🇮',
    currency: 'XOF',
    currencySymbol: 'CFA',
    currencyPosition: 'after',
    phonePrefix: '+225',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Abidjan', 'Yamoussoukro', 'Bouaké', 'Other'],
    timezone: 'Africa/Abidjan',
    enabled: true,
  },
  cm: {
    code: 'CM',
    name: 'Cameroon',
    flag: '🇨🇲',
    currency: 'XAF',
    currencySymbol: 'FCFA',
    currencyPosition: 'after',
    phonePrefix: '+237',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Yaoundé', 'Douala', 'Garoua', 'Other'],
    timezone: 'Africa/Douala',
    enabled: true,
  },
  cd: {
    code: 'CD',
    name: 'DR Congo',
    flag: '🇨🇩',
    currency: 'CDF',
    currencySymbol: 'FC',
    currencyPosition: 'after',
    phonePrefix: '+243',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Kinshasa', 'Lubumbashi', 'Goma', 'Other'],
    timezone: 'Africa/Kinshasa',
    enabled: true,
  },
  ao: {
    code: 'AO',
    name: 'Angola',
    flag: '🇦🇴',
    currency: 'AOA',
    currencySymbol: 'Kz',
    currencyPosition: 'after',
    phonePrefix: '+244',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Luanda', 'Huambo', 'Benguela', 'Other'],
    timezone: 'Africa/Luanda',
    enabled: true,
  },
  mz: {
    code: 'MZ',
    name: 'Mozambique',
    flag: '🇲🇿',
    currency: 'MZN',
    currencySymbol: 'MT',
    currencyPosition: 'after',
    phonePrefix: '+258',
    phoneLength: 9,
    paymentMethods: ['mpesa', 'stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Maputo', 'Beira', 'Nampula', 'Other'],
    timezone: 'Africa/Maputo',
    enabled: true,
  },
  mg: {
    code: 'MG',
    name: 'Madagascar',
    flag: '🇲🇬',
    currency: 'MGA',
    currencySymbol: 'Ar',
    currencyPosition: 'after',
    phonePrefix: '+261',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Antananarivo', 'Toamasina', 'Other'],
    timezone: 'Indian/Antananarivo',
    enabled: true,
  },
  zm: {
    code: 'ZM',
    name: 'Zambia',
    flag: '🇿🇲',
    currency: 'ZMW',
    currencySymbol: 'ZK',
    currencyPosition: 'before',
    phonePrefix: '+260',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Lusaka', 'Kitwe', 'Ndola', 'Other'],
    timezone: 'Africa/Lusaka',
    enabled: true,
  },
  bw: {
    code: 'BW',
    name: 'Botswana',
    flag: '🇧🇼',
    currency: 'BWP',
    currencySymbol: 'P',
    currencyPosition: 'before',
    phonePrefix: '+267',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Gaborone', 'Francistown', 'Other'],
    timezone: 'Africa/Gaborone',
    enabled: true,
  },
  na: {
    code: 'NA',
    name: 'Namibia',
    flag: '🇳🇦',
    currency: 'NAD',
    currencySymbol: 'N$',
    currencyPosition: 'before',
    phonePrefix: '+264',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Windhoek', 'Walvis Bay', 'Other'],
    timezone: 'Africa/Windhoek',
    enabled: true,
  },
  rw: {
    code: 'RW',
    name: 'Rwanda',
    flag: '🇷🇼',
    currency: 'RWF',
    currencySymbol: 'FRw',
    currencyPosition: 'after',
    phonePrefix: '+250',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Kigali', 'Other'],
    timezone: 'Africa/Kigali',
    enabled: true,
  },
  mu: {
    code: 'MU',
    name: 'Mauritius',
    flag: '🇲🇺',
    currency: 'MUR',
    currencySymbol: '₨',
    currencyPosition: 'before',
    phonePrefix: '+230',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Port Louis', 'Other'],
    timezone: 'Indian/Mauritius',
    enabled: true,
  },
  // ============ ADDITIONAL EUROPEAN COUNTRIES ============
  pt: {
    code: 'PT',
    name: 'Portugal',
    flag: '🇵🇹',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+351',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Lisbon', 'Porto', 'Algarve', 'Other'],
    timezone: 'Europe/Lisbon',
    enabled: true,
  },
  be: {
    code: 'BE',
    name: 'Belgium',
    flag: '🇧🇪',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+32',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Brussels', 'Flanders', 'Wallonia', 'Other'],
    timezone: 'Europe/Brussels',
    enabled: true,
  },
  ch: {
    code: 'CH',
    name: 'Switzerland',
    flag: '🇨🇭',
    currency: 'CHF',
    currencySymbol: 'CHF',
    currencyPosition: 'before',
    phonePrefix: '+41',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Zürich', 'Geneva', 'Basel', 'Bern', 'Other'],
    timezone: 'Europe/Zurich',
    enabled: true,
  },
  at: {
    code: 'AT',
    name: 'Austria',
    flag: '🇦🇹',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+43',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Vienna', 'Salzburg', 'Tyrol', 'Other'],
    timezone: 'Europe/Vienna',
    enabled: true,
  },
  pl: {
    code: 'PL',
    name: 'Poland',
    flag: '🇵🇱',
    currency: 'PLN',
    currencySymbol: 'zł',
    currencyPosition: 'after',
    phonePrefix: '+48',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Other'],
    timezone: 'Europe/Warsaw',
    enabled: true,
  },
  cz: {
    code: 'CZ',
    name: 'Czech Republic',
    flag: '🇨🇿',
    currency: 'CZK',
    currencySymbol: 'Kč',
    currencyPosition: 'after',
    phonePrefix: '+420',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Prague', 'Brno', 'Ostrava', 'Other'],
    timezone: 'Europe/Prague',
    enabled: true,
  },
  hu: {
    code: 'HU',
    name: 'Hungary',
    flag: '🇭🇺',
    currency: 'HUF',
    currencySymbol: 'Ft',
    currencyPosition: 'after',
    phonePrefix: '+36',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Budapest', 'Debrecen', 'Szeged', 'Other'],
    timezone: 'Europe/Budapest',
    enabled: true,
  },
  ro: {
    code: 'RO',
    name: 'Romania',
    flag: '🇷🇴',
    currency: 'RON',
    currencySymbol: 'lei',
    currencyPosition: 'after',
    phonePrefix: '+40',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Other'],
    timezone: 'Europe/Bucharest',
    enabled: true,
  },
  bg: {
    code: 'BG',
    name: 'Bulgaria',
    flag: '🇧🇬',
    currency: 'BGN',
    currencySymbol: 'лв',
    currencyPosition: 'after',
    phonePrefix: '+359',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Sofia', 'Plovdiv', 'Varna', 'Other'],
    timezone: 'Europe/Sofia',
    enabled: true,
  },
  gr: {
    code: 'GR',
    name: 'Greece',
    flag: '🇬🇷',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+30',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Athens', 'Thessaloniki', 'Crete', 'Other'],
    timezone: 'Europe/Athens',
    enabled: true,
  },
  hr: {
    code: 'HR',
    name: 'Croatia',
    flag: '🇭🇷',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+385',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Zagreb', 'Split', 'Rijeka', 'Other'],
    timezone: 'Europe/Zagreb',
    enabled: true,
  },
  rs: {
    code: 'RS',
    name: 'Serbia',
    flag: '🇷🇸',
    currency: 'RSD',
    currencySymbol: 'дин',
    currencyPosition: 'after',
    phonePrefix: '+381',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Belgrade', 'Novi Sad', 'Niš', 'Other'],
    timezone: 'Europe/Belgrade',
    enabled: true,
  },
  ua: {
    code: 'UA',
    name: 'Ukraine',
    flag: '🇺🇦',
    currency: 'UAH',
    currencySymbol: '₴',
    currencyPosition: 'after',
    phonePrefix: '+380',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Kyiv', 'Kharkiv', 'Odesa', 'Lviv', 'Other'],
    timezone: 'Europe/Kyiv',
    enabled: true,
  },
  se: {
    code: 'SE',
    name: 'Sweden',
    flag: '🇸🇪',
    currency: 'SEK',
    currencySymbol: 'kr',
    currencyPosition: 'after',
    phonePrefix: '+46',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Stockholm', 'Gothenburg', 'Malmö', 'Other'],
    timezone: 'Europe/Stockholm',
    enabled: true,
  },
  no: {
    code: 'NO',
    name: 'Norway',
    flag: '🇳🇴',
    currency: 'NOK',
    currencySymbol: 'kr',
    currencyPosition: 'after',
    phonePrefix: '+47',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Oslo', 'Bergen', 'Trondheim', 'Other'],
    timezone: 'Europe/Oslo',
    enabled: true,
  },
  dk: {
    code: 'DK',
    name: 'Denmark',
    flag: '🇩🇰',
    currency: 'DKK',
    currencySymbol: 'kr',
    currencyPosition: 'after',
    phonePrefix: '+45',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Copenhagen', 'Aarhus', 'Odense', 'Other'],
    timezone: 'Europe/Copenhagen',
    enabled: true,
  },
  fi: {
    code: 'FI',
    name: 'Finland',
    flag: '🇫🇮',
    currency: 'EUR',
    currencySymbol: '€',
    currencyPosition: 'after',
    phonePrefix: '+358',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Helsinki', 'Tampere', 'Turku', 'Other'],
    timezone: 'Europe/Helsinki',
    enabled: true,
  },
  ru: {
    code: 'RU',
    name: 'Russia',
    flag: '🇷🇺',
    currency: 'RUB',
    currencySymbol: '₽',
    currencyPosition: 'after',
    phonePrefix: '+7',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Other'],
    timezone: 'Europe/Moscow',
    enabled: true,
  },
  // ============ ADDITIONAL ASIAN COUNTRIES ============
  cn: {
    code: 'CN',
    name: 'China',
    flag: '🇨🇳',
    currency: 'CNY',
    currencySymbol: '¥',
    currencyPosition: 'before',
    phonePrefix: '+86',
    phoneLength: 11,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Beijing', 'Shanghai', 'Guangdong', 'Sichuan', 'Other'],
    timezone: 'Asia/Shanghai',
    enabled: true,
  },
  jp: {
    code: 'JP',
    name: 'Japan',
    flag: '🇯🇵',
    currency: 'JPY',
    currencySymbol: '¥',
    currencyPosition: 'before',
    phonePrefix: '+81',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Other'],
    timezone: 'Asia/Tokyo',
    enabled: true,
  },
  kr: {
    code: 'KR',
    name: 'South Korea',
    flag: '🇰🇷',
    currency: 'KRW',
    currencySymbol: '₩',
    currencyPosition: 'before',
    phonePrefix: '+82',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Other'],
    timezone: 'Asia/Seoul',
    enabled: true,
  },
  th: {
    code: 'TH',
    name: 'Thailand',
    flag: '🇹🇭',
    currency: 'THB',
    currencySymbol: '฿',
    currencyPosition: 'before',
    phonePrefix: '+66',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Other'],
    timezone: 'Asia/Bangkok',
    enabled: true,
  },
  vn: {
    code: 'VN',
    name: 'Vietnam',
    flag: '🇻🇳',
    currency: 'VND',
    currencySymbol: '₫',
    currencyPosition: 'after',
    phonePrefix: '+84',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Other'],
    timezone: 'Asia/Ho_Chi_Minh',
    enabled: true,
  },
  bd: {
    code: 'BD',
    name: 'Bangladesh',
    flag: '🇧🇩',
    currency: 'BDT',
    currencySymbol: '৳',
    currencyPosition: 'before',
    phonePrefix: '+880',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Dhaka', 'Chittagong', 'Khulna', 'Other'],
    timezone: 'Asia/Dhaka',
    enabled: true,
  },
  lk: {
    code: 'LK',
    name: 'Sri Lanka',
    flag: '🇱🇰',
    currency: 'LKR',
    currencySymbol: 'Rs',
    currencyPosition: 'before',
    phonePrefix: '+94',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Colombo', 'Kandy', 'Galle', 'Other'],
    timezone: 'Asia/Colombo',
    enabled: true,
  },
  np: {
    code: 'NP',
    name: 'Nepal',
    flag: '🇳🇵',
    currency: 'NPR',
    currencySymbol: 'रू',
    currencyPosition: 'before',
    phonePrefix: '+977',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Kathmandu', 'Pokhara', 'Other'],
    timezone: 'Asia/Kathmandu',
    enabled: true,
  },
  mm: {
    code: 'MM',
    name: 'Myanmar',
    flag: '🇲🇲',
    currency: 'MMK',
    currencySymbol: 'K',
    currencyPosition: 'after',
    phonePrefix: '+95',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Yangon', 'Mandalay', 'Other'],
    timezone: 'Asia/Yangon',
    enabled: true,
  },
  kh: {
    code: 'KH',
    name: 'Cambodia',
    flag: '🇰🇭',
    currency: 'KHR',
    currencySymbol: '៛',
    currencyPosition: 'after',
    phonePrefix: '+855',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Phnom Penh', 'Siem Reap', 'Other'],
    timezone: 'Asia/Phnom_Penh',
    enabled: true,
  },
  ir: {
    code: 'IR',
    name: 'Iran',
    flag: '🇮🇷',
    currency: 'IRR',
    currencySymbol: '﷼',
    currencyPosition: 'after',
    phonePrefix: '+98',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Tehran', 'Isfahan', 'Shiraz', 'Other'],
    timezone: 'Asia/Tehran',
    enabled: true,
  },
  iq: {
    code: 'IQ',
    name: 'Iraq',
    flag: '🇮🇶',
    currency: 'IQD',
    currencySymbol: 'ع.د',
    currencyPosition: 'after',
    phonePrefix: '+964',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Baghdad', 'Basra', 'Erbil', 'Other'],
    timezone: 'Asia/Baghdad',
    enabled: true,
  },
  jo: {
    code: 'JO',
    name: 'Jordan',
    flag: '🇯🇴',
    currency: 'JOD',
    currencySymbol: 'د.ا',
    currencyPosition: 'after',
    phonePrefix: '+962',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Amman', 'Irbid', 'Zarqa', 'Other'],
    timezone: 'Asia/Amman',
    enabled: true,
  },
  lb: {
    code: 'LB',
    name: 'Lebanon',
    flag: '🇱🇧',
    currency: 'LBP',
    currencySymbol: 'ل.ل',
    currencyPosition: 'after',
    phonePrefix: '+961',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'COMMUNITY', 'OTHER'],
    provinces: ['Beirut', 'Tripoli', 'Other'],
    timezone: 'Asia/Beirut',
    enabled: true,
  },
  kw: {
    code: 'KW',
    name: 'Kuwait',
    flag: '🇰🇼',
    currency: 'KWD',
    currencySymbol: 'د.ك',
    currencyPosition: 'after',
    phonePrefix: '+965',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Kuwait City', 'Other'],
    timezone: 'Asia/Kuwait',
    enabled: true,
  },
  qa: {
    code: 'QA',
    name: 'Qatar',
    flag: '🇶🇦',
    currency: 'QAR',
    currencySymbol: 'ر.ق',
    currencyPosition: 'after',
    phonePrefix: '+974',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Doha', 'Other'],
    timezone: 'Asia/Qatar',
    enabled: true,
  },
  bh: {
    code: 'BH',
    name: 'Bahrain',
    flag: '🇧🇭',
    currency: 'BHD',
    currencySymbol: 'ب.د',
    currencyPosition: 'after',
    phonePrefix: '+973',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Manama', 'Other'],
    timezone: 'Asia/Bahrain',
    enabled: true,
  },
  om: {
    code: 'OM',
    name: 'Oman',
    flag: '🇴🇲',
    currency: 'OMR',
    currencySymbol: 'ر.ع',
    currencyPosition: 'after',
    phonePrefix: '+968',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'COMMUNITY', 'OTHER'],
    provinces: ['Muscat', 'Other'],
    timezone: 'Asia/Muscat',
    enabled: true,
  },
  // ============ ADDITIONAL AMERICAN COUNTRIES ============
  cl: {
    code: 'CL',
    name: 'Chile',
    flag: '🇨🇱',
    currency: 'CLP',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+56',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Santiago', 'Valparaíso', 'Concepción', 'Other'],
    timezone: 'America/Santiago',
    enabled: true,
  },
  pe: {
    code: 'PE',
    name: 'Peru',
    flag: '🇵🇪',
    currency: 'PEN',
    currencySymbol: 'S/',
    currencyPosition: 'before',
    phonePrefix: '+51',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Lima', 'Arequipa', 'Cusco', 'Other'],
    timezone: 'America/Lima',
    enabled: true,
  },
  ec: {
    code: 'EC',
    name: 'Ecuador',
    flag: '🇪🇨',
    currency: 'USD',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+593',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Quito', 'Guayaquil', 'Cuenca', 'Other'],
    timezone: 'America/Guayaquil',
    enabled: true,
  },
  ve: {
    code: 'VE',
    name: 'Venezuela',
    flag: '🇻🇪',
    currency: 'VES',
    currencySymbol: 'Bs',
    currencyPosition: 'before',
    phonePrefix: '+58',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Caracas', 'Maracaibo', 'Valencia', 'Other'],
    timezone: 'America/Caracas',
    enabled: true,
  },
  uy: {
    code: 'UY',
    name: 'Uruguay',
    flag: '🇺🇾',
    currency: 'UYU',
    currencySymbol: '$U',
    currencyPosition: 'before',
    phonePrefix: '+598',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Montevideo', 'Other'],
    timezone: 'America/Montevideo',
    enabled: true,
  },
  py: {
    code: 'PY',
    name: 'Paraguay',
    flag: '🇵🇾',
    currency: 'PYG',
    currencySymbol: '₲',
    currencyPosition: 'before',
    phonePrefix: '+595',
    phoneLength: 9,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Asunción', 'Other'],
    timezone: 'America/Asuncion',
    enabled: true,
  },
  bo: {
    code: 'BO',
    name: 'Bolivia',
    flag: '🇧🇴',
    currency: 'BOB',
    currencySymbol: 'Bs',
    currencyPosition: 'before',
    phonePrefix: '+591',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['La Paz', 'Santa Cruz', 'Cochabamba', 'Other'],
    timezone: 'America/La_Paz',
    enabled: true,
  },
  pa: {
    code: 'PA',
    name: 'Panama',
    flag: '🇵🇦',
    currency: 'PAB',
    currencySymbol: 'B/.',
    currencyPosition: 'before',
    phonePrefix: '+507',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Panama City', 'Other'],
    timezone: 'America/Panama',
    enabled: true,
  },
  cr: {
    code: 'CR',
    name: 'Costa Rica',
    flag: '🇨🇷',
    currency: 'CRC',
    currencySymbol: '₡',
    currencyPosition: 'before',
    phonePrefix: '+506',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['San José', 'Other'],
    timezone: 'America/Costa_Rica',
    enabled: true,
  },
  gt: {
    code: 'GT',
    name: 'Guatemala',
    flag: '🇬🇹',
    currency: 'GTQ',
    currencySymbol: 'Q',
    currencyPosition: 'before',
    phonePrefix: '+502',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Guatemala City', 'Other'],
    timezone: 'America/Guatemala',
    enabled: true,
  },
  hn: {
    code: 'HN',
    name: 'Honduras',
    flag: '🇭🇳',
    currency: 'HNL',
    currencySymbol: 'L',
    currencyPosition: 'before',
    phonePrefix: '+504',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Tegucigalpa', 'San Pedro Sula', 'Other'],
    timezone: 'America/Tegucigalpa',
    enabled: true,
  },
  sv: {
    code: 'SV',
    name: 'El Salvador',
    flag: '🇸🇻',
    currency: 'USD',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+503',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['San Salvador', 'Other'],
    timezone: 'America/El_Salvador',
    enabled: true,
  },
  ni: {
    code: 'NI',
    name: 'Nicaragua',
    flag: '🇳🇮',
    currency: 'NIO',
    currencySymbol: 'C$',
    currencyPosition: 'before',
    phonePrefix: '+505',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Managua', 'Other'],
    timezone: 'America/Managua',
    enabled: true,
  },
  cu: {
    code: 'CU',
    name: 'Cuba',
    flag: '🇨🇺',
    currency: 'CUP',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+53',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Havana', 'Other'],
    timezone: 'America/Havana',
    enabled: true,
  },
  dom: {
    code: 'DO',
    name: 'Dominican Republic',
    flag: '🇩🇴',
    currency: 'DOP',
    currencySymbol: 'RD$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Santo Domingo', 'Santiago', 'Other'],
    timezone: 'America/Santo_Domingo',
    enabled: true,
  },
  pr: {
    code: 'PR',
    name: 'Puerto Rico',
    flag: '🇵🇷',
    currency: 'USD',
    currencySymbol: '$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['San Juan', 'Other'],
    timezone: 'America/Puerto_Rico',
    enabled: true,
  },
  jm: {
    code: 'JM',
    name: 'Jamaica',
    flag: '🇯🇲',
    currency: 'JMD',
    currencySymbol: 'J$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Kingston', 'Montego Bay', 'Other'],
    timezone: 'America/Jamaica',
    enabled: true,
  },
  tt: {
    code: 'TT',
    name: 'Trinidad and Tobago',
    flag: '🇹🇹',
    currency: 'TTD',
    currencySymbol: 'TT$',
    currencyPosition: 'before',
    phonePrefix: '+1',
    phoneLength: 10,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Port of Spain', 'Other'],
    timezone: 'America/Port_of_Spain',
    enabled: true,
  },
  // ============ ADDITIONAL OCEANIA COUNTRIES ============
  pg: {
    code: 'PG',
    name: 'Papua New Guinea',
    flag: '🇵🇬',
    currency: 'PGK',
    currencySymbol: 'K',
    currencyPosition: 'before',
    phonePrefix: '+675',
    phoneLength: 8,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Port Moresby', 'Other'],
    timezone: 'Pacific/Port_Moresby',
    enabled: true,
  },
  fj: {
    code: 'FJ',
    name: 'Fiji',
    flag: '🇫🇯',
    currency: 'FJD',
    currencySymbol: 'FJ$',
    currencyPosition: 'before',
    phonePrefix: '+679',
    phoneLength: 7,
    paymentMethods: ['stripe'],
    categories: ['BREAKING', 'CRIME', 'POLITICS', 'PROTEST', 'WEATHER', 'COMMUNITY', 'OTHER'],
    provinces: ['Suva', 'Other'],
    timezone: 'Pacific/Fiji',
    enabled: true,
  },
}

// Get enabled countries only
export function getEnabledCountries(): Record<string, CountryConfig> {
  return Object.fromEntries(
    Object.entries(countries).filter(([, config]) => config.enabled)
  )
}

// Get all country codes
export function getCountryCodes(): string[] {
  return Object.keys(countries)
}

// Get enabled country codes
export function getEnabledCountryCodes(): string[] {
  return Object.keys(getEnabledCountries())
}

// Check if a country code is valid
export function isValidCountry(code: string): boolean {
  return code in countries
}

// Check if a country is enabled
export function isCountryEnabled(code: string): boolean {
  return countries[code]?.enabled ?? false
}

// Get country config by code
export function getCountryConfig(code: string): CountryConfig | null {
  return countries[code] || null
}

// Format price for a country
export function formatPrice(cents: number, countryCode: string): string {
  const config = countries[countryCode]
  if (!config) return `${cents / 100}`

  const amount = (cents / 100).toFixed(2)
  return config.currencyPosition === 'before'
    ? `${config.currencySymbol}${amount}`
    : `${amount}${config.currencySymbol}`
}

// Validate phone number for a country
export function isValidPhoneForCountry(phone: string, countryCode: string): boolean {
  const config = countries[countryCode]
  if (!config) return false

  // Remove all non-digits
  const digits = phone.replace(/\D/g, '')

  // Check if starts with country code (without +)
  const prefix = config.phonePrefix.replace('+', '')

  if (digits.startsWith(prefix)) {
    // International format: +27821234567
    return digits.length === prefix.length + config.phoneLength
  } else if (digits.startsWith('0')) {
    // Local format: 0821234567
    return digits.length === config.phoneLength + 1
  } else {
    // Just the number: 821234567
    return digits.length === config.phoneLength
  }
}

// Format phone to international format
export function formatPhoneForCountry(phone: string, countryCode: string): string {
  const config = countries[countryCode]
  if (!config) return phone

  // Remove all non-digits
  let digits = phone.replace(/\D/g, '')

  // Remove leading zero
  if (digits.startsWith('0')) {
    digits = digits.substring(1)
  }

  // Remove country code if present
  const prefix = config.phonePrefix.replace('+', '')
  if (digits.startsWith(prefix)) {
    digits = digits.substring(prefix.length)
  }

  return `${config.phonePrefix}${digits}`
}

// Default country (for redirects)
export const DEFAULT_COUNTRY = 'sa'
